import nltk

#nltk.download()

base = [
('gosto desse lugar','alegria'),
('que paisagem bonita','alegria'),
('isso me deixou muito feliz','alegria'),
('adoro sorvete','alegria'),
('me amarro em ver o por do sol','alegria'),
('estamos maravilhados','alegria'),
('comecei a ler um novo livro','alegria'),
('o novo filme foi incrível','alegria'),
('curti o elogio obrigado','alegria'),
('foi muito bom ter comido aquela pizza ontem','alegria'),
('me sinto completamente amado','alegria'),
('estou me sentindo muito animado novamente','alegria'),
('mandamos muito bem hoje','alegria'),
('que belo dia para dirigir um carro novo','alegria'),
('estou contente com o resultado do teste que fiz no dia de ontem','alegria'),
('o amor e lindo','alegria'),
('fiquei animado com a noticia nova','alegria'),
('gosto de ficar no seu aconchego','alegria'),
('somo tão amáveis um com o outro','alegria'),
('sinto uma grande afeição por ele','alegria'),
('quero agradar meus filhos','alegria'),
('eu amo você','alegria'),
('amar é maravilhoso','alegria'),
('me sinto muito bem','alegria'),
('como o luar é belo','alegria'),
('nossa como sou afortunado','alegria'),
('o dia esta muito bonito','alegria'),
('nossa como sou afortunado','alegria'),
('as maravilhas do mundo','alegria'),
('recebi muito carinho hoje do meus colegas','alegria'),
('estou me sentindo reconfortada hoje','alegria'),
('é muito bom estar com os amigos','alegria'),
('que bondade a sua em vir aqui','alegria'),
('essa é a melhor escolhas de todas','alegria'),
('o mais incrível é você minha bela','alegria'),
('é emocionante estar aqui','alegria'),
('eu estou sorrindo de orelha a orelha','alegria'),
('que sorriso bonito','alegria'),
('adoro este doce de frutas','alegria'),
('meu suco favorito','alegria'),
('estou agradecida pela ajuda','alegria'),
('agradeço voce por estar aqui','alegria'),
('prazer ter você em nossa equipe','alegria'),
('trabalhar em equipe é o melhor','alegria'),
('somos compatíveis um com o outro','alegria'),
('o órgão é compatível com o paciente','alegria'),
('estou contente fui aceita na faculdade','alegria'),
('fui aprovada no meu exame','alegria'),
('fui beneficiada pela minha empresa','alegria'),
('eu sou muito cativante','alegria'),
('estou contente com o apoio','alegria'),
('como este lugar e confortável','alegria'),
('e bom estar quente neste frio','alegria'),
('vou te chamar para comemorar','alegria'),
('sou muito grata a você','alegria'),
('você significa muito para mim','alegria'),
('você me atrai facilmente','alegria'),
('aquele rapaz e extremamente atraente','alegria'),
('com todo esse charme você irá atrair a todos','alegria'),
('nossa como você é charmoso querido','alegria'),
('sou querida pelos meu amigos','alegria'),
('seja cuidadoso com os meus sentimentos','alegria'),
('estou comovido com tamanha caridade','alegria'),
('um chá quente e reconfortante','alegria'),
('que alegria ter vocês aqui','alegria'),
('vamos aplaudir o vencedor','alegria'),
('palmas para a aniversariante','alegria'),
('desejo a você tudo de bom','alegria'),
('hora de apreciar um bom vinho','alegria'),
('aprecio sua presença em minha escola','alegria'),
('adoro seu cabelo macio','alegria'),
('adoro a cor dos seus olhos','alegria'),
('sou muito afortunado','alegria'),
('é benéfico para todos esta nova medida','alegria'),
('ficou lindo','alegria'),
('achei esse sapato muito simpático','alegria'),
('congratulações pelo seu aniversário','alegria'),
('a música é linda','alegria'),
('concluí uma tarefa muito difícil','alegria'),
('concluí minha graduação','alegria'),
('e um prazer conhecê-lo','alegria'),
('o coleguismo de vocês é animador','alegria'),
('estou aproveitando as férias','alegria'),
('vamos aproveitar as férias','alegria'),
('e muito divertido este jogo','alegria'),
('vamos ter muita diversão','alegria'),
('não achei que me divertiria tanto assim','alegria'),
('eu adorei este perfume','alegria'),
('sua bondade é cativante','alegria'),
('estou despreocupada','alegria'),
('estimo muito o seu trabalho','alegria'),
('somos estimados por nossa família','alegria'),
('concretizamos nossa ideia','alegria'),
('nosso ideal foi alcançado','alegria'),
('estamos muito felizes juntos','alegria'),
('estou tão animada com os preparativos para o casamento','alegria'),
('voce será muito amado meu filho','alegria'),
('os apaixonados são maravilhosos','alegria'),
('agradeço imensamente o seu apoio nestes dias','alegria'),
('estamos namorando','alegria'),
('estou namorando este vestido a um tempo','alegria'),
('pude comprar meu celular hoje','alegria'),
('e um deleite poder compartilhar minhas vitórias','alegria'),
('ela e uma boa garota','alegria'),
('maravilhoso jogo amistoso','alegria'),
('nos curtimos muito o passeio','alegria'),
('essa viagem foi sensacional','alegria'),
('ficaremos felizes amanha com o sol previsto','alegria'),
('adoro fazer compras','alegria'),
('amo dirigir a noite','alegria'),
('nada melhor que um churrasco com uma bebida','alegria'),
('que comida deliciosa','alegria'),
('a feijoada e muito saborosa','alegria'),
('comida mineira tem um sabor incrível','alegria'),
('hoje consegui relaxar','alegria'),
('ele ficou bem relaxado na sombra','alegria'),
('fiquei feliz em te ver denovo','alegria'),
('o cheiro da chuva me faz muito bem','alegria'),
('nos sentimos bem','alegria'),
('gostamos do novo drink do bar','alegria'),
('curtimos muito o programa com os amigos','alegria'),
('estar com amigos e muito bom','alegria'),
('que filme legal o de ontem','alegria'),
('esse espaço e melhor que o outro','alegria'),
('gosto de patinar e brincar','alegria'),
('passear de barco e bom','alegria'),
('tomar café me faz bem','alegria'),
('tomar banho e relaxante','alegria'),
('surfar e lindo','alegria'),
('que por do sol lindo','alegria'),
('ficar bonita e se sentir bem','alegria'),
('as rosas são lindo presente','alegria'),
('dançar e um ótimo exercicio','alegria'),
('comer chocolate e maravilhoso','alegria'),
('fazer aniversario com festa','alegria'),
('parabens para voce','alegria'),
('feliz aniversario amigo','alegria'),
('ir a praia deixa eles alegres','alegria'),
('o natal e uma epoca que me deixa muito alegre','alegria'),
('o carnaval e sinonimo de alegria','alegria'),
('a excursao foi diversão pura','alegria'),
('ir no parque e divertido demais','alegria'),
('vamos comemorar a sua promoção','alegria'),
('consegui um novo emprego e comemoramos','alegria'),
('isso e uma ocasiao que deve ser comemorada','alegria'),
('comemorei a chegada dele ontem','alegria'),
('ganhei a competição','alegria'),
('ganhamos um vale presente para ir onde quiser','alegria'),
('jogar hoje me deu uma sensação muito boa','alegria'),
('a conversa foi muito boa','alegria'),
('o papo esta bom demais','alegria'),
('essa vista me deixou bem demais','alegria'),
('esses oculos me deixaram bonito','alegria'),
('voce e uma pessoa incrivel','alegria'),
('eu adoro ficar ao seu lado','alegria'),
('passamos a estada bem','alegria'),
('fomos bem alimentados','alegria'),
('adoro ir a praia','alegria'),
('estou animado para o fim de semana','alegria'),
('a viagem esta chegando','alegria'),
('que pessoa incrivel','alegria'),
('carro lindo esse','alegria'),
('que restaurante lindo','alegria'),
('que vista linda','alegria'),
('comer la foi legal demais','alegria'),
('que experiencia legal para ir com as crianças','alegria'),
('feliz aniversario','alegria'),
('parabens pelo seu aniversario','alegria'),
('gostei muito de ter lido esse livro','alegria'),
('foi um momento legal','alegria'),
('acordei feliz hoje','alegria'),
('estou animada para o passeio de barco','alegria'),
('muito bom poder ir a opera','alegria'),
('bom demais esse sol no fim de semana','alegria'),
('isso e uma coisa boa','alegria'),
('que tempo gostoso','alegria'),
('uma sensação muito gostosa','alegria'),
('e muito bom ver voce denovo','alegria'),
('que por do sol sensacional','alegria'),
('me amarro em tomar sunday','alegria'),
('curti o seu comentario','alegria'),
('estou animado para hoje a noite','alegria'),
('vai ser incrivel','alegria'),

('eu imploro não me matem!','medo'),
('tem certeza que não é perigoso?','medo'),
('não é seguro','medo'),
('tenho que correr pra não me pegarem','medo'),
('socorro ele queria roubar os meus doces','medo'),
('esse cara está me perseguindo','medo'),
('não entro lá é um lugar muito perigoso','medo'),
('este lugar continua assustador','medo'),
('na selva tem muitos animais perigosos','medo'),
('avancem com cautela','medo'),
('este lugar está silencioso de mais cuidado','medo'),
('por favor deixe-me viver','medo'),
('vou ficar sem mesada se tirar nota baixa','medo'),
('eu nao posso perder','medo'),
('nao quero que isso aconteça','medo'),
('nao me deixe sozinho','medo'),
('nao quero te perder','medo'),
('parece que tem olhos nos vigiando','medo'),
('os bandidos estao vigiando','medo'),
('eu temo que a sentença do juiz possa ser negativa','medo'),
('nos tememos o resultado do teste','medo'),
('mas essa missão é arriscada','medo'),
('essa area e muito arriscada','medo'),
('parece arriscado demais','medo'),
('se salve antes que seja tarde','medo'),
('salvem-se quem puder','medo'),
('não tive culpa juro não fui eu','medo'),
('tenho que tomar cuidado com o lobisomem','medo'),
('meu deus ele desapareceu','medo'),
('que horror','medo'),
('nossa foi um horror passar por isso','medo'),
('aquela cara me deixou muito assustado','medo'),
('estou assustada com tudo isso','medo'),
('mantenha isso em segredo se descobrirem estaremos ferrados','medo'),
('estou ouvindo passos atrás de mim','medo'),
('eu vou pedir socorro','medo'),
('cuidado com as curvas na estrada','medo'),
('cuidado ele morde','medo'),
('não sei parece perigoso','medo'),
('estou tremendo de medo','medo'),
('estamos com muito medo deles','medo'),
('passamos por coisas aterrorizantes','medo'),
('foi um terror ir ate la','medo'),
('ouço passos na minha direção','medo'),
('acho que está arriscado de mais','medo'),
('vamos voltar é muito perigoso','medo'),
('fuja se não acabaremos mortos','medo'),
('essa substancia pode nos matar','medo'),
('aquela arma vai nos matar','medo'),
('corremos um serio risco de morte','medo'),
('receio por não me livrar desta situação','medo'),
('socorro ele está armado','medo'),
('ei cuidado você vai bater no poste','medo'),
('socorro nós estamos afundando','medo'),
('e sério cuidado com essa arma','medo'),
('os tubarões estão atacando','medo'),
('sinto arrepios quando fico sozinho no escuro','medo'),
('ligeiro temos que fugir depressa','medo'),
('fuja o tigre parece faminto','medo'),
('estou sem saída preciso de um milagre','medo'),
('tire isso de mim! socorro','medo'),
('não sei nadar vou me afogar','medo'),
('não tenho certeza se e seguro','medo'),
('vou apanhar se meus pais verem meu boletim','medo'),
('iremos apanhar daquela gangue','medo'),
('não consigo sair daqui','medo'),
('me tire daqui','medo'),
('se sair tão tarde poderei ser assaltada','medo'),
('temo pela sua segurança','medo'),
('eu te entrego o dinheiro por favor não me mate','medo'),
('não quero nem pensar no que pode acontecer','medo'),
('nessa cidade é uma desgraça atrás da outra','medo'),
('alguém esta me ligando estou assustado','medo'),
('isso não é remedio não me matem','medo'),
('eu não confio nele tenho que ter cautela','medo'),
('muita cautela','medo'),
('receio que terei de ir','medo'),
('a noite e muito perigosa','medo'),
('estou estremecendo com essa casa','medo'),
('olha aquela criatura se movendo monstruosamente','medo'),
('não aguento este suspense','medo'),
('estou chocado e amedrontado com este assassinato brutal','medo'),
('nao quero ficar de frente com o assassino','medo'),
('políticos usam suas forças para afugentar e amedrontar o povo','medo'),
('o objetivo disso e apenas me amedrontar mais','medo'),
('isso me apavora','medo'),
('que abominável esse monstro!','medo'),
('vamos alarmar a todos sobre a situação','medo'),
('estou amedrontada','medo'),
('estou com muito medo da noite','medo'),
('ele esta me ameaçando a dias','medo'),
('quanta angústia','medo'),
('estou angustiada','medo'),
('angustiadamente vou sair de casa','medo'),
('estou assustado com as atitudes do meu colega','medo'),
('agora se sente humilhado apavorado','medo'),
('assustou a população e provocou mortes','medo'),
('estou com dificuldades para respirar e muito assustado','medo'),
('os policiais se amedrontaram quando o carro capotou','medo'),
('o trabalhador é assombrado pelo temor do desemprego','medo'),
('este lugar é mal assombrado','medo'),
('estou assombrado pela crise financeira','medo'),
('mesmo aterrorizado lembro de você','medo'),
('aterrorizado e suando frio','medo'),
('um grupo de elefantes selvagens tem aterrorizado vilas','medo'),
('me sinto intimidada pela sua presença','medo'),
('tenho medo de ser advertida novamente','medo'),
('estou correndo o risco de ser advertido','medo'),
('estou correndo riscos','medo'),
('os riscos são reais','medo'),
('podemos perder muito dinheiro com essa investida','medo'),
('socorro fui intimado a depor','medo'),
('fui notificado e estou com medo de perder a guarda da minha filha','medo'),
('estou angustiada com meus filhos na rua','medo'),
('e abominável o que fazem com os animais','medo'),
('foi terrível o tigre quase o matou','medo'),
('me advertiram sobre isso','medo'),
('esse ferimento vai doer','medo'),
('estou com muito dor','medo'),
('estamos desesperados hoje','medo'),
('sentir desespero não e uma coisa boa','medo'),
('ele tinha medo da morte','medo'),
('nos vamos morrer','medo'),
('tenho horror a aranhas','medo'),
('ele teve horrores noturnos','medo'),
('essa situação vai ser terrivel','medo'),
('que batida terrivel','medo'),
('ela e muito amedrontada','medo'),
('elas sairam amedrontadas do trem fantasma','medo'),
('fastasmas dão medo demais','medo'),
('eu tive medo de ir ate aquele lugar','medo'),
('ela teve medo de ir falar com ele','medo'),
('que susto você me deu','medo'),
('essa noite esta bem estranha','medo'),
('que coisa mais estranha aquela que aconteceu','medo'),
('nao estou me sentindo bem','medo'),
('nao vamos porque nao estamos nos sentindo bem','medo'),
('tem algo de errado com o planeta','medo'),
('algo esta muito errado em toda essa situação','medo'),
('eu tenho medo de dar errado','medo'),
('a floresta passa um ar estranho','medo'),
('o estranho me deixou com medo','medo'),
('eles tem pavor de cobras','medo'),
('pavor tomou conta do corpo dela','medo'),
('ela tem pavor de altura','medo'),
('temos fobia de lugares escuros','medo'),
('ele tem fobia de altura','medo'),
('ela tem fobia de lugares fechados','medo'),
('eu tenho fobia de espaços apertados','medo'),
('uma fobia muito forte','medo'),
('tinhamos fobia de aranhas','medo'),
('em frente ao leão ficamos em pânico','medo'),
('uma sensação de pânico tomou conta de mim','medo'),
('você entrou em pânico','medo'),
('ela entrou em pânico e começou a gritar','medo'),
('ouvimos tiros e o pânico tomou conta','medo'),
('ele ficou em pânico e começou a chorar','medo'),
('o pânico tomou conta de todos','medo'),
('entramos em pânico ao mesmo tempo','medo'),
('choramos de medo e pânico','medo'),
('não entrem em pânico','medo'),
('o temor tomou conta de nos','medo'),
('tememos o fim','medo'),
('eu temo que a ação não ocorra','medo'),
('eles temem o fim de tudo','medo'),
('temia que acontecesse','medo'),
('temi o rosto do assassino','medo'),
('temem o encerramento','medo'),
('temia a noite quando criança','medo'),
('eu temo que o clima fique pior','medo'),
('todos temerão o nome','medo'),
('eu tenho pavor a palhaços','medo'),
('ele tinha medo de filmes de terror','medo'),
('ela tem horror a altura','medo'),
('levamos um baita susto','medo'),
('as pessoas sairam amedrontadas do trem fantasma','medo'),
('falavam com ele com receio','medo'),
('depois que tudo apagou ficaram apavoradas','medo'),
('tenho fobia de falar em público','medo'),
('manifestou horror a prisão','medo'),
('crianças são medrosas','medo'),

('por favor não me abandone','tristeza'),
('não quero ficar sozinha','tristeza'),
('não me deixe sozinha','tristeza'),
('estou abatida','tristeza'),
('ele esta todo abatido','tristeza'),
('tão triste suas palavras','tristeza'),
('estou aborrecida','tristeza'),
('isso vai me aborrecer','tristeza'),
('estou com muita aflição','tristeza'),
('me aflige o modo como fala','tristeza'),
('estou em agonia com meu intimo','tristeza'),
('não quero fazer nada','tristeza'),
('não quero fazer nada','tristeza'),
('não consigo parar de chorar','tristeza'),
('não consigo segurar as lagrimas','tristeza'),
('e muita dor perder um ente querido','tristeza'),
('estou realmente arrependida','tristeza'),
('acho que o carma volta, pois agora sou eu quem sofro','tristeza'),
('você não cumpriu suas promessas','tristeza'),
('me sinto amargurado','tristeza'),
('coitado esta tão triste','tristeza'),
('nosso amor acabou','tristeza'),
('essa noite machuca só para mim','tristeza'),
('quando eu penso em você realmente dói','tristeza'),
('como se fosse nada você vê minhas lagrimas','tristeza'),
('você disse cruelmente que não se arrependeu','tristeza'),
('eu nunca mais vou te ver','tristeza'),
('ela esta com depressão','tristeza'),
('a depressão aflige as pessoas','tristeza'),
('estar depressivo e muito ruim','tristeza'),
('estou derrotada e deprimida depois deste dia','tristeza'),
('como me sinto culpada','tristeza'),
('a ansiedade tomou conta de mim','tristeza'),
('as pessoas não gostam do meu jeito','tristeza'),
('adeus passamos bons momentos juntos','tristeza'),
('sinto sua falta','tristeza'),
('ele não gostou da minha comida','tristeza'),
('estou sem dinheiro para a comida','tristeza'),
('queria que fosse o ultimo dia da minha vida','tristeza'),
('você está com vergonha de mim','tristeza'),
('ela não aceitou a minha proposta','tristeza'),
('reprovei de ano na faculdade','tristeza'),
('afinal você só sabe me desfazer','tristeza'),
('eu falhei em tudo nessa vida','tristeza'),
('eu fui muito humilhado','tristeza'),
('e uma história muito triste','tristeza'),
('ninguem acredita em mim','tristeza'),
('eu não sirvo para nada mesmo','tristeza'),
('droga, não faço nada direito','tristeza'),
('sofrimento em dobro na minha vida','tristeza'),
('fui demitida essa semana','tristeza'),
('as crianças sofrem ainda mais que os adultos','tristeza'),
('pra mim um dia e ruim, o outro e pior','tristeza'),
('de repente perdi o apetite','tristeza'),
('oh que dia infeliz','tristeza'),
('estamos afundados em contas','tristeza'),
('nem um milagre pode nos salvar','tristeza'),
('só me resta a esperança','tristeza'),
('pior que isso não pode ficar','tristeza'),
('meu salário e baixo','tristeza'),
('não passei no vestibular','tristeza'),
('ninguem se importa comigo','tristeza'),
('ninguem lembrou do meu aniversário','tristeza'),
('tenho tanto azar','tristeza'),
('o gosto da vingança e amargo','tristeza'),
('sou uma mulher amargurada depois de que você me deixou','tristeza'),
('estou desanimada com a vida','tristeza'),
('e um desanimo só coitadinha','tristeza'),
('a derrota e depressiva','tristeza'),
('discriminar e desumano','tristeza'),
('que desanimo','tristeza'),
('e uma desonra para o pais','tristeza'),
('a preocupação deveria nos levar a ação não a depressão','tristeza'),
('passamos ao desalento e a loucura','tristeza'),
('aquele que nunca viu a tristeza nunca reconhecerá a alegria','tristeza'),
('cuidado com a tristeza ela e um vicio','tristeza'),
('estou me sentindo um tanto podre, então não sou muito ambicioso agora','tristeza'),
('estou atualizando meu blog porque me sinto uma merda','tristeza'),

('eu nunca a separo de mim porque eu nunca quero que ela se sinta envergonhada dela','tristeza'),
('eu estava me sentindo um pouco vaidoso quando fiz este','tristeza'),
('sinto-me maravilhosamente emocionado sabendo que essas mulheres de quem eu conhecia apenas um punhado estavam segurando a mim e ao meu baba em nossa jornada','tristeza'),
('eu estava me sentindo tão destroçado quanto tenho certeza de que Katniss estava','tristeza'),
('sinto que meu único papel agora seria rasgar suas velas com meu pessimismo e descontentamento','tristeza'),
('não tenho certeza se o sentimento de perda um dia irá embora, mas pode se transformar em um doce sentimento de nostalgia pelo que eu compartilhei nesta vida com meu pai e a sorte que tive de ter um pai por anos','tristeza'),
('eu também digo a você na esperança de que qualquer pessoa que ainda se sinta estigmatizada ou envergonhada por seus problemas de saúde mental, deixe de lado o estigma, deixe de lado a vergonha',' tristeza'),
('não me sinto culpado como se não fosse ser capaz de cozinhar para ele','tristeza'),
('eu roubei um livro de um dos meus autores favoritos de todos os tempos e agora me sinto uma pessoa podre','tristeza'),
('eu começo a me sentir emocional','tristeza'),
('me sinto com defeito ou algo assim por não querer ter um bebê','tristeza'),
('passei as últimas duas semanas de escola me sentindo miserável','tristeza'),
('me sinto humilhado, envergonhado ou tolo','tristeza'),
('sinto que devo concordar com ela, embora possa imaginar alguns casos possíveis bastante desagradáveis','tristeza'),
('estava triste pela partida deles','tristeza'),
('estamos tristes pelo fim da serie','tristeza'),
('tristeza não e bom','tristeza'),
('o verão vai acabar e junto vem a tristeza','tristeza'),
('o filme me deixou triste','tristeza'),
('porque você esta triste','tristeza'),
('perdeu o emprego e ficou triste','tristeza'),
('tristeza tomou conta dele todo','tristeza'),
('saber disso me abalou','tristeza'),
('com a morte dele ficamos abalados','tristeza'),
('o fim nos abalou','tristeza'),
('a catastrofe deixou todos abalados','tristeza'),
('ela ficou muito abalada com o fim do relacionamento','tristeza'),
('estamos abalados em saber','tristeza'),
('nos abalou muito com toda certeza','tristeza'),
('estou meio melacolico','tristeza'),
('uma melancolia abateu todos nos','tristeza'),
('nao fique melancolica garota','tristeza'),
('essa ansiedade me corroi por dentro','tristeza'),
('fiquei em um estado muito depressivo','tristeza'),
('ela esta depressiva','tristeza'),
('eles tem depressao','tristeza'),
('a ansiedade faz deles pessoas infelizes','tristeza'),
('a depressao faz delas pessoas infelizes','tristeza'),
('com depressao acaba que não faço nada','tristeza'),
('a ansiedade me atrapalha muito','tristeza'),
('perder a vontade de fazer qualquer coisa e ter depressao','tristeza'),
('e pessimo nao controlar a ansiedade','tristeza'),
('perder a casa nos deixou infelizes','tristeza'),
('ficamos infelizes por estarmos trancados','tristeza'),
('ela e infeliz no casamento','tristeza'),
('a falta de sol me deixa infeliz','tristeza'),
('infelizmente nada deu certo','tristeza'),
('nada deu certo para ela e ela ficou infeliz','tristeza'),
('infelicidade foi extrema depois da morte','tristeza'),
('infelizmente nao correu como esperavamos','tristeza'),
('estava infeliz onde eu estava','tristeza'),
('a infelicidade tomou conta de mim','tristeza'),
('olhar aquela cena me deixou aflito','tristeza'),
('ela esta aflita esperando pela noticia','tristeza'),
('algumas ações deles me afligem','tristeza'),
('saber dessa noticia me deixou em choque','tristeza'),
('ver aquela cena nos comoveu muito','tristeza'),
('fiquei comovido com a historia de vida deles','tristeza'),
('ela ficou comovida','tristeza'),
('ficamos comovidos ao ver as vitimas do acidente','tristeza'),
('isso nos comoveu muito com toda certeza','tristeza'),
('nos comovemos com o choro dela','tristeza'),
('que triste saber disso','tristeza'),
('nossa hoje estou muito triste','tristeza'),
('triste em saber que ela morreu','tristeza'),
('fiquei triste depois que você brigou comigo','tristeza'),
('não fique triste','tristeza'),
('a tristeza bateu muito forte','tristeza'),
('a tristeza tomou conta do ambiente','tristeza'),
('estavamos chorando porque estavamos muito tristes','tristeza'),
('ela ficou triste depois de ver o filme','tristeza'),
('triste fim a banda teve','tristeza'),
('a criança chorou depois de cair','tristeza'),
('choramos ao final da serie','tristeza'),
('choramos muito ao saber da noticia','tristeza'),
('ela começou a chorar quando lembrou dele','tristeza'),
('ele começou a chorar ao saber do termino do relacionamento','tristeza'),
('choramos por conta da dor','tristeza'),
('não consigo parar de chorar','tristeza'),
('a pessoa esta chorando','tristeza'),
('ela esta soluçando de tanto chorar','tristeza'),
('a criança ralou o joelho e chorou','tristeza'),
('as lágrimas vêm do coração, não da razão','tristeza'),
('pior tipo de tristeza é aquela que não conseguimos explicar','tristeza'),
('lágrima que mais dói não é aquela que cai do rosto','tristeza'),
('decepção aliada a tristeza e o mais cruel dos sentimentos','tristeza'),
('cansado de tentar, cansado de chorar','tristeza'),
('dói muito manter uma luz acesa para alguém que nunca voltará','tristeza'),
('sozinho e sem nada','tristeza'),
('são tempos difíceis para os sonhadores','tristeza'),
('decepcionar com a vida só não é pior do que me decepcionar com você','tristeza'),
('ter um coração mole em um mundo tão duro só me traz dor e sofrimento','tristeza'),
('as pessoas ficam me dizendo que a vida continua, mas para mim, essa é a pior parte','tristeza'),
('quando a dor vem de dentro, ela é ainda mais forte','tristeza'),
('quando você partiu, todo o meu mundo veio a baixo','tristeza'),
('minha decepção tem nome, data de nascimento e endereço','tristeza'),
('eu gostaria de ser suficiente para alguém, mas parece que isso não é possível','tristeza'),
('cada dia é uma nova decepção','tristeza'),
('está cada vez mais difícil esconder a dor','tristeza'),
('como um isqueiro sem gás, está difícil acender uma chama dentro de mim','tristeza'),
('a pior solidão é estar com alguém e ainda assim se sentir solitário','tristeza'),
('nada nos deixa tão vulneráveis quanto a decepção','tristeza'),

('ele a feriu profundamente','raiva'),
('vou despejar minha cólera em você','raiva'),
('me sinto atormentado','raiva'),
('não me contrarie','raiva'),
('vou destruir tudo  que foi construído','raiva'),
('não consigo terminar este trabalho, e muito frustrante','raiva'),
('me frustra a sua presença aqui','raiva'),
('esta comida me parece muito ruim','raiva'),
('você me destrói','raiva'),
('estamos separados','raiva'),
('estou odiando este vestido','raiva'),
('não pude comprar meu celular hoje','raiva'),
('ela e uma garota ruim','raiva'),
('estivemos em um show horroroso','raiva'),
('o ingresso estava muito caro','raiva'),
('se eu estragar tudo vai por água a baixo','raiva'),
('não possuo dinheiro algum','raiva'),
('sou muito pobre','raiva'),
('vai prejudicar a todos esta nova medida','raiva'),
('ficou ridículo','raiva'),
('este sapato esta muito apertado','raiva'),
('a musica e uma ofensa aos meus ouvidos','raiva'),
('não consigo terminar uma tarefa muito difícil','raiva'),
('reprovei em minha graduação','raiva'),
('estou muito chateado com tudo','raiva'),
('eu odeio em você','raiva'),
('e um desprazer conhecê-lo','raiva'),
('estou desperdiçando minhas ferias','raiva'),
('e muito ruim este jogo','raiva'),
('vamos ter muito rancor pela frente','raiva'),
('não achei que seria tão terrível','raiva'),
('vou vetar o orçamento ao cliente','raiva'),
('meus pais não consentiram nosso casamento','raiva'),
('eu odiei este perfume','raiva'),
('seu descaso e frustrante','raiva'),
('me sinto completamente amarga','raiva'),
('desprezo muito o seu trabalho','raiva'),
('estamos descontentes por nossa família','raiva'),
('vou infernizar a sua empresa','raiva'),
('estou furioso com estes valores','raiva'),
('obrigaram o rapaz a sair','raiva'),
('como ele pode deixar de lado?','raiva'),
('são apenas injurias sobre mim','raiva'),
('estou enfurecido com a situação dessa empresa','raiva'),
('estou com o diabo no corpo','raiva'),
('isso foi diabólico','raiva'),
('tenho aversão à gente chata','raiva'),
('não vou perdoar sua traição','raiva'),
('esse dinheiro sujo e corrupto','raiva'),
('eles me crucificam o tempo todo','raiva'),
('eu vou enlouquecer com todo este barulho','raiva'),
('não agüento todo esse assedio','raiva'),
('cólera do dragão','raiva'),
('isso e ridículo','raiva'),
('da próxima vez, vou inventar tudo sozinho','raiva'),
('seus tolos deixaram ele escapar','raiva'),
('jamais te perdoarei','raiva'),
('o que e isso outra multa','raiva'),
('você passou dos limites','raiva'),
('sente-se e cale a boca','raiva'),
('ingratosvermesvocês me pagam','raiva'),
('saiam da dai, se não arranco vocês dai','raiva'),
('você já me causou problemas suficientes','raiva'),
('isso foi a gota d’agua','raiva'),
('o que você tem com isso?','raiva'),
('não vejo a hora de me livrar de você','raiva'),
('já entendi a jogada seus safados','raiva'),
('você não merece piedade','raiva'),
('saia de perto de mim','raiva'),
('suma daqui, ou arranco seu couro','raiva'),
('estou revoltado com essa situação','raiva'),
('seu idiota!','raiva'),
('não, eu não vou te emprestar dinheiro!','raiva'),
('você não passa de um cafajeste! vai embora','raiva'),
('pare de frescura e vá trabalhar','raiva'),
('eles merecem uma lição','raiva'),
('ainda estou muito bravo com você','raiva'),
('eu preciso surrar aquela chantagista','raiva'),
('olha o que você fez derramou','raiva'),
('você está pedindo pra apanhar','raiva'),
('me deixa em paz','raiva'),
('morra maldito, morra','raiva'),
('você e mais irritante de perto','raiva'),
('e bom fechar o bico','raiva'),
('cala a boca seu idiota','raiva'),
('mais que merda foi essa','raiva'),
('que saco tudo esta acontecendo de errado','raiva'),
('puta que pariu não aguento mais isso','raiva'),
('porra esse som me deixa com raiva','raiva'),
('uma merda tudo que esta acontecendo','raiva'),
('eu tenho vontade socar a sua cara','raiva'),
('eu não teria que controlar a minha raiva se as pessoas aprendessem a controlar a estupidez','raiva'),
('tem gente que não adianta mandar para o inferno','raiva'),
('odeio lições de moral','raiva'),
('nossa como eu estou puto com você','raiva'),
('você esta passando dos limites','raiva'),
('estamos perdendo a paciência com você','raiva'),
('tomei raiva de você','raiva'),
('meu ódio por isso é eterno','raiva'),
('odeio chorar','raiva'),
('estou com muita vontade de bater em você','raiva'),
('essa situação e foda','raiva'),
('foda-se ele não se importa','raiva'),
('dia lindo para tacar fogo em alguém','raiva'),
('puta que pariu que saco isso','raiva'),
('so estou afim de jogar na sua cara','raiva'),
('e uma pena não poder dar o dedo do meio','raiva'),
('um dedo do meio para você','raiva'),
('a vai se ferrar','raiva'),
('não perguntamos sua opinião','raiva'),
('cuide da sua vida','raiva'),
('não se meta na minha vida','raiva'),
('eu não tenho mais tempo para perder com isso','raiva'),
('as pessoas são estúpidas demais','raiva'),
('a vontade de te quebrar e grande','raiva'),
('dane-se','raiva'),
('eu quero dar um tapa em você','raiva'),
('nunca fale de mim pelas costas','raiva'),
('a situação so faz passar raiva','raiva'),
('você e burro ou oque','raiva'),
('nao se faça de burra','raiva'),
('que babaca','raiva'),
('o idiota para de ser ignorante','raiva'),
('odeio o começo da semana','raiva'),
('te odeio com todas as forças','raiva'),
('odeio bater o pe na quina do movel','raiva'),
('odeio engarrafamento','raiva'),
('odeio ser obrigado a assistir esse filme','raiva'),
('mas que merda bati o carro','raiva'),
('que merda e essa que você esta fazendo','raiva'),
('para com essa merda','raiva'),
('odeio esperar consulta','raiva'),
('não gosto desse comportamento','raiva'),
('não gostamos de musica alta','raiva'),
('ela nao gosta de esperar','raiva'),
('não gosto de criticas','raiva'),
('não gosto de ser comparado','raiva'),
('detesto essa cidade','raiva'),
('detesto o trânsito pesado','raiva'),
('detestamos pessoas de mal carater','raiva'),
('ela detesta ficar presa','raiva'),
('detesto ficar doente','raiva'),
('tenho raiva de ficar mal','raiva'),
('tenho raiva de falsidade','raiva'),
('temos raiva de pessoas falsas','raiva'),
('ele tem raiva de cobrar os que os outros devem','raiva'),
('ela tem raiva do chefe','raiva'),
('tenho raiva de tumultos','raiva'),
('temos raiva de lugares cheios','raiva'),
('fico furioso com idiotice','raiva'),
('fica furiosa com ele','raiva'),
('ouvir isso me deixou bravo','raiva'),
('fico bravo com nao pontualidade','raiva'),
('fica brava quando não fazem seu trabalho','raiva'),
('fico bravo com atendimento ruim','raiva'),
('ficam bravas quando o transito engarrafa','raiva'),
('que porcaria você esta fazendo','raiva'),
('não gosto desse trabalho e uma porcaria','raiva'),
('pegar ônibus cheio e uma porcaria','raiva'),
('gastei dinheiro a toa que porcaria','raiva'),
('furei o pneu em uma rua deserta que porcaria','raiva'),
('que saco esse vizinho barulhento','raiva'),
('que saco esse som alto','raiva'),
('mas que saco esse calor forte','raiva'),
('nossa como eu odeio esse comportamento','raiva'),
('odeio birra de crianças','raiva'),
('odeio imitações baratas','raiva'),
('odeio clima quente demais','raiva'),
('detesto não ter dinheiro','raiva'),
('detesto cobrar dividas','raiva'),
('tenho raiva de gente falsa','raiva'),
('tenho raiva do meu vizinho','raiva'),
('tenho odio de pessoas sem palavra','raiva'),
('detesto pessoas sem dignidade','raiva'),
('não de uma de otário','raiva'),
('não seja otária','raiva'),
('pare com essa incompetencia','raiva'),
('detesto ser chamado a atenção','raiva'),
('você esta me deixando com raiva','raiva'),
('me molhei todo que raiva','raiva')]
stopwordsnltk = nltk.corpus.stopwords.words('portuguese')


def removestopwords(texto):
    frases = []
    for (palavras, emocao) in texto:
        semstop = [p for p in palavras.split() if p not in stopwordsnltk]
        frases.append((semstop, emocao))
    return frases



def aplicastemmer(texto):
    stemmer = nltk.stem.RSLPStemmer()
    frasesstemming = []
    for (palavras, emocao) in texto:
        comstemming = [str(stemmer.stem(p)) for p in palavras.split() if p not in stopwordsnltk]
        frasesstemming.append((comstemming, emocao))
    return frasesstemming

frasescomstemming = aplicastemmer(base)


def buscapalavras(frases):
    todaspalavras = []
    for (palavras, emocao) in frases:
        todaspalavras.extend(palavras)
    return todaspalavras

palavras = buscapalavras(frasescomstemming)


def buscafrequencia(palavras):
    palavras = nltk.FreqDist(palavras)
    return palavras

frequencia = buscafrequencia(palavras)


def buscapalavrasunicas(frequencia):
    freq = frequencia.keys()
    return freq

palavrasunicas = buscapalavrasunicas(frequencia)


def extratorpalavras(documento):
    doc = set(documento)
    caracteristicas = {}
    for palavra in palavrasunicas:
        caracteristicas['%s' % palavra] = (palavra in doc)
    return caracteristicas
caracteristicasfrase = extratorpalavras(['tim', 'gole', 'nov'])



basecompleta = nltk.classify.apply_features(extratorpalavras, frasescomstemming)


classificador = nltk.NaiveBayesClassifier.train(basecompleta)

teste = 'fico puto com isso cara'
teste_stemming = []
stemmer = nltk.stem.RSLPStemmer()
for (palavras) in teste.split():
    filtrado = [e for e in palavras.split()]
    teste_stemming.append(str(stemmer.stem(filtrado[0])))

print(classificador.classify(extratorpalavras(teste_stemming)))



